// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ixoja/library/internal/models"
)

// CreateBookOKCode is the HTTP code returned for type CreateBookOK
const CreateBookOKCode int = 200

/*CreateBookOK OK

swagger:response createBookOK
*/
type CreateBookOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewCreateBookOK creates CreateBookOK with default headers values
func NewCreateBookOK() *CreateBookOK {

	return &CreateBookOK{}
}

// WithPayload adds the payload to the create book o k response
func (o *CreateBookOK) WithPayload(payload *models.Book) *CreateBookOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create book o k response
func (o *CreateBookOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
