// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBooksIDOKCode is the HTTP code returned for type DeleteBooksIDOK
const DeleteBooksIDOKCode int = 200

/*DeleteBooksIDOK OK

swagger:response deleteBooksIdOK
*/
type DeleteBooksIDOK struct {
}

// NewDeleteBooksIDOK creates DeleteBooksIDOK with default headers values
func NewDeleteBooksIDOK() *DeleteBooksIDOK {

	return &DeleteBooksIDOK{}
}

// WriteResponse to the client
func (o *DeleteBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
