// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBookOKCode is the HTTP code returned for type DeleteBookOK
const DeleteBookOKCode int = 200

/*DeleteBookOK OK

swagger:response deleteBookOK
*/
type DeleteBookOK struct {
}

// NewDeleteBookOK creates DeleteBookOK with default headers values
func NewDeleteBookOK() *DeleteBookOK {

	return &DeleteBookOK{}
}

// WriteResponse to the client
func (o *DeleteBookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
