// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ixoja/library/internal/models"
)

// GetBooksIDOKCode is the HTTP code returned for type GetBooksIDOK
const GetBooksIDOKCode int = 200

/*GetBooksIDOK OK

swagger:response getBooksIdOK
*/
type GetBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewGetBooksIDOK creates GetBooksIDOK with default headers values
func NewGetBooksIDOK() *GetBooksIDOK {

	return &GetBooksIDOK{}
}

// WithPayload adds the payload to the get books Id o k response
func (o *GetBooksIDOK) WithPayload(payload *models.Book) *GetBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id o k response
func (o *GetBooksIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
