// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/ixoja/library/internal/models"
)

// GetBooksHandlerFunc turns a function with the right signature into a get books handler
type GetBooksHandlerFunc func(GetBooksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBooksHandlerFunc) Handle(params GetBooksParams) middleware.Responder {
	return fn(params)
}

// GetBooksHandler interface for that can handle valid get books params
type GetBooksHandler interface {
	Handle(GetBooksParams) middleware.Responder
}

// NewGetBooks creates a new http.Handler for the get books operation
func NewGetBooks(ctx *middleware.Context, handler GetBooksHandler) *GetBooks {
	return &GetBooks{Context: ctx, Handler: handler}
}

/*GetBooks swagger:route GET /books getBooks

Get list of all books.

*/
type GetBooks struct {
	Context *middleware.Context
	Handler GetBooksHandler
}

func (o *GetBooks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBooksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetBooksOKBody get books o k body
// swagger:model GetBooksOKBody
type GetBooksOKBody struct {

	// books
	Books []*models.Book `json:"books"`
}

// Validate validates this get books o k body
func (o *GetBooksOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBooks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBooksOKBody) validateBooks(formats strfmt.Registry) error {

	if swag.IsZero(o.Books) { // not required
		return nil
	}

	for i := 0; i < len(o.Books); i++ {
		if swag.IsZero(o.Books[i]) { // not required
			continue
		}

		if o.Books[i] != nil {
			if err := o.Books[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getBooksOK" + "." + "books" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBooksOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBooksOKBody) UnmarshalBinary(b []byte) error {
	var res GetBooksOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
