// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBooksOKCode is the HTTP code returned for type GetBooksOK
const GetBooksOKCode int = 200

/*GetBooksOK OK

swagger:response getBooksOK
*/
type GetBooksOK struct {

	/*
	  In: Body
	*/
	Payload *GetBooksOKBody `json:"body,omitempty"`
}

// NewGetBooksOK creates GetBooksOK with default headers values
func NewGetBooksOK() *GetBooksOK {

	return &GetBooksOK{}
}

// WithPayload adds the payload to the get books o k response
func (o *GetBooksOK) WithPayload(payload *GetBooksOKBody) *GetBooksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books o k response
func (o *GetBooksOK) SetPayload(payload *GetBooksOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
