// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAllBooksParams creates a new GetAllBooksParams object
// no default values defined in spec.
func NewGetAllBooksParams() GetAllBooksParams {

	return GetAllBooksParams{}
}

// GetAllBooksParams contains all the bound params for the get all books operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllBooks
type GetAllBooksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllBooksParams() beforehand.
func (o *GetAllBooksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
