// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/ixoja/library/internal/models"
)

// GetAllBooksHandlerFunc turns a function with the right signature into a get all books handler
type GetAllBooksHandlerFunc func(GetAllBooksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllBooksHandlerFunc) Handle(params GetAllBooksParams) middleware.Responder {
	return fn(params)
}

// GetAllBooksHandler interface for that can handle valid get all books params
type GetAllBooksHandler interface {
	Handle(GetAllBooksParams) middleware.Responder
}

// NewGetAllBooks creates a new http.Handler for the get all books operation
func NewGetAllBooks(ctx *middleware.Context, handler GetAllBooksHandler) *GetAllBooks {
	return &GetAllBooks{Context: ctx, Handler: handler}
}

/*GetAllBooks swagger:route GET /books getAllBooks

Get list of all books.

*/
type GetAllBooks struct {
	Context *middleware.Context
	Handler GetAllBooksHandler
}

func (o *GetAllBooks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllBooksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAllBooksOKBody get all books o k body
// swagger:model GetAllBooksOKBody
type GetAllBooksOKBody struct {

	// books
	Books []*models.Book `json:"books"`
}

// Validate validates this get all books o k body
func (o *GetAllBooksOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBooks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllBooksOKBody) validateBooks(formats strfmt.Registry) error {

	if swag.IsZero(o.Books) { // not required
		return nil
	}

	for i := 0; i < len(o.Books); i++ {
		if swag.IsZero(o.Books[i]) { // not required
			continue
		}

		if o.Books[i] != nil {
			if err := o.Books[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getAllBooksOK" + "." + "books" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAllBooksOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllBooksOKBody) UnmarshalBinary(b []byte) error {
	var res GetAllBooksOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
