// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchBooksIDOKCode is the HTTP code returned for type PatchBooksIDOK
const PatchBooksIDOKCode int = 200

/*PatchBooksIDOK OK

swagger:response patchBooksIdOK
*/
type PatchBooksIDOK struct {
}

// NewPatchBooksIDOK creates PatchBooksIDOK with default headers values
func NewPatchBooksIDOK() *PatchBooksIDOK {

	return &PatchBooksIDOK{}
}

// WriteResponse to the client
func (o *PatchBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
