// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ixoja/library/internal/models"
)

// PostBooksOKCode is the HTTP code returned for type PostBooksOK
const PostBooksOKCode int = 200

/*PostBooksOK OK

swagger:response postBooksOK
*/
type PostBooksOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewPostBooksOK creates PostBooksOK with default headers values
func NewPostBooksOK() *PostBooksOK {

	return &PostBooksOK{}
}

// WithPayload adds the payload to the post books o k response
func (o *PostBooksOK) WithPayload(payload *models.Book) *PostBooksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books o k response
func (o *PostBooksOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
