// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// UpdateBookHandlerFunc turns a function with the right signature into a update book handler
type UpdateBookHandlerFunc func(UpdateBookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateBookHandlerFunc) Handle(params UpdateBookParams) middleware.Responder {
	return fn(params)
}

// UpdateBookHandler interface for that can handle valid update book params
type UpdateBookHandler interface {
	Handle(UpdateBookParams) middleware.Responder
}

// NewUpdateBook creates a new http.Handler for the update book operation
func NewUpdateBook(ctx *middleware.Context, handler UpdateBookHandler) *UpdateBook {
	return &UpdateBook{Context: ctx, Handler: handler}
}

/*UpdateBook swagger:route PATCH /books/{id} updateBook

Update book record.

*/
type UpdateBook struct {
	Context *middleware.Context
	Handler UpdateBookHandler
}

func (o *UpdateBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateBookParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateBookBody update book body
// swagger:model UpdateBookBody
type UpdateBookBody struct {

	// rating
	Rating string `json:"rating,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this update book body
func (o *UpdateBookBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateBookBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateBookBody) UnmarshalBinary(b []byte) error {
	var res UpdateBookBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
