// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateBookOKCode is the HTTP code returned for type UpdateBookOK
const UpdateBookOKCode int = 200

/*UpdateBookOK OK

swagger:response updateBookOK
*/
type UpdateBookOK struct {
}

// NewUpdateBookOK creates UpdateBookOK with default headers values
func NewUpdateBookOK() *UpdateBookOK {

	return &UpdateBookOK{}
}

// WriteResponse to the client
func (o *UpdateBookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
