swagger: '2.0'
info:
  title: Library API
  version: '1.0'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /books:
    get:
      operationId: getAllBooks
      summary: Get list of all books.
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              books:
                type: array
                items:
                  $ref: '#/definitions/book'
        500:
          description: Internal error.
          schema:
            $ref: "#/definitions/error"

    post:
      operationId: createBook
      summary: Create book record.
      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/book'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/book'
        400:
          description: Bad argument.
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error.
          schema:
            $ref: "#/definitions/error"

  /books/{id}:
    get:
      operationId: getBook
      summary: Returns book by id.
      parameters:
        - in: path
          name: id
          required: true
          type: string
          format: uuid
          description: book id
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/book'
        404:
          description: Not found.
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error.
          schema:
            $ref: "#/definitions/error"

    patch:
      operationId: updateBook
      summary: Update book record.
      parameters:
        - in: path
          name: id
          required: true
          type: string
          format: uuid
          description: book id
        - in: body
          name: bookUpdate
          required: true
          schema:
            type: object
            properties:
              rating:
                type: integer
                minimum: 1
                maximum: 3
              status:
                type: string
                enum: [ checked_in, checked_out ]
      responses:
        200:
          description: OK
        400:
          description: Bad argument.
          schema:
            $ref: "#/definitions/error"
        404:
          description: Not found.
          schema:
            $ref: "#/definitions/error"
        409:
          description: Conflict.
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error.
          schema:
            $ref: "#/definitions/error"

    delete:
      operationId: deleteBook
      summary: Delete book record.
      parameters:
        - in: path
          name: id
          required: true
          type: string
          format: uuid
          description: book id
      responses:
        200:
          description: OK
        404:
          description: Not found.
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error.
          schema:
            $ref: "#/definitions/error"

definitions:
  book:
    type: object
    properties:
      id:
        type: string
        format: uuid
      title:
        type: string
      author:
        type: string
      publisher:
        type: string
      publication_date:
        type: string
        format: date
      rating:
        type: object
        properties:
          rate:
            type: string
            enum: [ rate1, rate2, rate3 ]
          rate_precise:
            type: number
          rates_count:
            type: integer
      status:
        type: string
        enum: [ checked_in, checked_out ]
    required:
      - title
      - author
      - publisher
      - publication_date

  error:
    type: object
    properties:
      message:
        type: string